apiVersion: v1
kind: Service
metadata:
  name: banco-empleados-service
spec:
  selector:
    app: banco-empleados-api
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30003
